services:
  mongo:
    image: mongo:latest
    container_name: patient-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: patient-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  patient-management-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient-management-service-app
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - ./uploads:/app/uploads

volumes:
  mongo_data:
