server.port=8081
spring.application.name=patient-management-service
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/clinic_db}
spring.data.mongodb.auto-index-creation=true
file.upload-dir=${FILE_UPLOAD_DIR:./uploads}