server.port=8081
spring.application.name=patient-management-service
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://dbuser:dbuser2026@test.ubtlnvl.mongodb.net/clinic?appName=TEST}
spring.data.mongodb.auto-index-creation=true
file.upload-dir=${FILE_UPLOAD_DIR:./uploads}